console.log("Primeira linha \n Segunda linha")
console.log("O meu nome é 'Rafael'")
console.log('O nome dela é "Ingrid"')
console.log(`A multiplicação de 5 por 3 é ${5*3}`)
console.log("O" + " meu" + " nome" + " é" + " Rafael.")